name: kostin_p_b_l
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^3.0.1
  flutter_svg: ^0.22.0
  simple_shadow: ^0.2.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

assets:
  - assets/icons/
  - assets/images/
  - assets/

flutter: 
  uses-material-design: true

